### ISSUE TITLE
Example is with library 1.0.2

### ISSUE THREAD

**Issue by Sadmansamee** [barion/barion-ios-objc-app2app#1]
Is there any Obj-C or Swift(Preferred) example with 1.0.3

**Comment by mohalaci** [comment]
Sorry there is not swift example, but you can easily integrate it.

**Comment by Sadmansamee** [comment]
okhay. but can you please update the example to match with Library 1.0.3. Wanted to use latest version.

**Comment by mohalaci** [comment]
We are working on a new version of the library, we found some bugs and after this fixes we will update the example project too. Please be patient.

**Comment by mohalaci** [comment]
@Sadmansamee We updated the library and the example project too. Thank you for your patience.

**Comment by Sadmansamee** [comment]
thanks
